{% set name = "svgdigitizer" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/svgdigitizer-{{ version }}.tar.gz
  sha256: ff45a30e0350489c56f392eefcbc2d613dd6215e8751fd68b277a3746f665669

build:
  entry_points:
    - svgdigitizer=svgdigitizer.entrypoint:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - astropy >=5,<6
    # https://github.com/echemdb/svgdigitizer/issues/152
    - click >=8,<8.1
    - frictionless >=5.8.3,<6
    - matplotlib-base >=3.5,<4
    - mergedeep >=1.3.4,<2
    - pandas >=1.3,<2
    - pdf2image >=1.16,<2
    - pillow >=9,<10
    - pybtex >=0.24,<0.25
    - python >=3.9
    - pyyaml >=6,<7
    - scipy >=1.7,<2
    - svg.path >=4.1,<5
    - svgpathtools >=1.4,<2
    - svgwrite >=1.4,<2

test:
  imports:
    - svgdigitizer
  commands:
    - pip check
    - svgdigitizer --help
  requires:
    - pip

about:
  home: https://pypi.org/project/svgdigitizer/
  summary: svgdigitizer is a Python library and command line tool to recover the measured data underlying plots in scientific publications.
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://echemdb.github.io/svgdigitizer/
  dev_url: https://github.com/echemdb/svgdigitizer

extra:
  recipe-maintainers:
    - nicohoermann
    - linuxrider
    - DunklesArchipel
    - saraedum
