{% set name = "svgdigitizer" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/svgdigitizer-{{ version }}.tar.gz
  sha256: 4e031af096a76bd6315ad945ebae325c426f32a6a45df71b45abe67f52b2a1f5

build:
  entry_points:
    - svgdigitizer=svgdigitizer.__main__:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - astropy >=5,<6
    - click >=8,<9
    - frictionless >=4,<5
    - matplotlib-base >=3.5,<4
    - mergedeep >=1.3.4,<2
    - pandas >=1.3,<2
    - pdf2image >=1.16,<2
    - pillow >=8.4,<10
    - python >=3.9
    - pyyaml >=6,<7
    - scipy >=1.7,<2
    - svg.path >=4.1,<5
    - svgpathtools >=1.4,<2
    - svgwrite >=1.4,<2

test:
  imports:
    - svgdigitizer
  commands:
    - pip check
    - svgdigitizer --help
  requires:
    - pip

about:
  home: https://pypi.org/project/svgdigitizer/
  summary: svgdigitizer is a Python library and command line tool to recover the measured data underlying plots in scientific publications.
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://echemdb.github.io/svgdigitizer/
  dev_url: https://github.com/echemdb/svgdigitizer

extra:
  recipe-maintainers:
    - nicohoermann
    - linuxrider
    - DunklesArchipel
    - saraedum
